title: Shubham Saxena
logo: /assets/img/logo.png
description: I am a graduate of Dual Degree programme in Computer Science and Engineering, Indian Institute of Technology Kharagpur. I have an experience of working in EDA (Electronic Design Automation) and HFT (High Frequency Trading) domains in big multinational companies like Ansys, Synopsys, Blackrock, Mathisys and Divya Capital
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
